"""Add unique booking constraint

Revision ID: ead7ef293ce3
Revises: 2e00eab61a67
Create Date: 2026-06-29 13:02:54.525518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead7ef293ce3'
down_revision = '2e00eab61a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_trek_booking', ['user_id', 'trek_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_trek_booking', type_='unique')

    # ### end Alembic commands ###
